# Base Image
FROM osrf/ros:foxy-desktop

# Arguments
ARG USER=initial
ARG GROUP=initial
ARG UID=1000
ARG GID=${UID}
ARG SHELL=/bin/bash

# Install packages
RUN export DEBIAN_FRONTEND=noninteractive \
  && apt update \
  && apt install -y --no-install-recommends \
    # for developments
    wget curl ssh zsh terminator gnome-terminal git vim tig \
    # for nvidia driver
    dbus-x11 libglvnd0 libgl1 libglx0 libegl1 libxext6 libx11-6 \
    # for unity build
    node-gyp gconf-service lib32gcc1 lib32stdc++6 libasound2 libc6 libc6-i386 libcairo2 libcap2 libcups2 libdbus-1-3 \
    libexpat1 libfontconfig1 libfreetype6 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libgl1-mesa-glx libgl1 libglib2.0-0 \
    libglu1-mesa libglu1 libgtk2.0-0 libnspr4 libnss3 libpango1.0-0 libstdc++6 libx11-6 libxcomposite1 libxcursor1 \
    libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxtst6 zlib1g debconf npm fuse nautilus \
    ros-foxy-desktop \
    && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Node.js dependencies
RUN apt-get update && apt-get install -y curl sudo

# Node.js
RUN curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
RUN sudo apt-get install -y nodejs
RUN echo "NODE Version:" && node --version
RUN echo "NPM Version:" && npm --version

# http-server
RUN npm install --global http-server

# Env vars for the nvidia-container-runtime.
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute

# Setup users and groups
RUN groupadd --gid ${GID} ${GROUP} \
  && useradd --gid ${GID} --uid ${UID} -ms ${SHELL} ${USER} \
  && mkdir -p /etc/sudoers.d \
  && echo "${USER}:x:${UID}:${UID}:${USER},,,:$HOME:${shell}" >> /etc/passwd \
  && echo "${USER}:x:${UID}:" >> /etc/group \
  && echo "${USER} ALL=(ALL) NOPASSWD: ALL" > "/etc/sudoers.d/${USER}" \
  && chmod 0440 "/etc/sudoers.d/${USER}"

# copy entrypoint
COPY entrypoint.bash /entrypoint.bash
RUN chmod 777 /entrypoint.bash

# setup terminator config
RUN mkdir -p /home/${USER}/.config/terminator
COPY config/terminator/config /home/${USER}/.config/terminator
RUN sudo chown -R ${USER}:${GROUP} /home/${USER}/.config

# Switch user to ${USER}
USER ${USER}

# Make SSH available
EXPOSE 22

# Switch to user's HOME folder
WORKDIR /home/${USER}

# Micro-XRCE-DDS-Agent
RUN git clone https://github.com/eProsima/Micro-XRCE-DDS-Agent.git \
  && cd Micro-XRCE-DDS-Agent \
  && git checkout v1.3.0 \
  && mkdir build && cd build \
  && sudo -s source /opt/ros/foxy/setup.bash \
  && cmake .. \
  && make \
  && sudo make install
RUN sudo ldconfig /usr/local/lib/

# ros2-web-bridge
RUN git clone https://github.com/RobotWebTools/ros2-web-bridge.git
RUN ["/bin/bash", "-c", "cd ros2-web-bridge && source /opt/ros/foxy/setup.bash && npm install"]

# get untiy-hub
RUN mkdir unity \
  && cd unity \
  && wget https://public-cdn.cloud.unity3d.com/hub/prod/UnityHub.AppImage \
  && chown -R ${USER}:${GID} /home/${USER}/unity \
  && chmod +x /home/${USER}/unity/UnityHub.AppImage

# install VScode
RUN wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg \
&& sudo install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/ \
&& sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list' \
&& rm -f packages.microsoft.gpg
RUN sudo apt install apt-transport-https \
&& sudo apt update -y \
&& sudo apt install code -y

# CMD ["terminator"]
ENTRYPOINT ["/entrypoint.bash", "terminator"]

